version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./directus-data:/directus/database
    environment:
      KEY: mysecretkey
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      DB_CLIENT: sqlite
    restart: always
